# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db42d865cffd13f9ee6a161fc3d65df672142bce4932847374472f0f9219f496159596799fa0b58004b53f4a2d56c21dafdf25a9e90112ac88a42d023987eb3f

test:
  secret_key_base: 54f60f82f8bf7eac25684f5e22ce68a8a5f053643ad69451eaa109bf28ae3d87f8599060918f680d9b68d71a40751ecf5e800546b5b1c762d836a7b2b78c8cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
